### ISSUE TITLE
ModuleNotFoundError: No module named 'digitalio'

### ISSUE THREAD

**Issue by lboue** [adafruit/circuitmatter#20]
Hello,

Since this commit b21b35f366b16651358ab362ec3c6f2e73410f9a I am facing this module issue:
```
# python3 -m examples.circuitmatter_simpletest
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/circuitmatter/examples/circuitmatter_simpletest.py", line 6, in <module>
    import digitalio
ModuleNotFoundError: No module named 'digitalio'
```

https://github.com/adafruit/circuitmatter/blob/818c9e6a7d7f1b94b61bc0cfbe99e3f326974c46/examples/circuitmatter_simpletest.py#L6

We should explain in README how to install [digitalio](https://docs.circuitpython.org/en/latest/shared-bindings/digitalio/index.html) module.

**Comment by tannewt** [comment]
Yup, I'm working on this today by trying to get it going on a Raspberry Pi Zero 2.

You can make a separate example for the temp sensor now. The `replay.py` file does what the old `__main__.py` did.
